whalex:
  module: com.meiya.whalex.db.module.graph.GremlinDriverServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.graph.GremlinDriverConfigHelper
  param: com.meiya.whalex.db.util.param.impl.graph.GremlinDriverParamUtil