whalex:
  module: com.meiya.whalex.db.module.graph.NebulaGraphServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.graph.NebulaGraphConfigHelper
  param: com.meiya.whalex.db.util.param.impl.graph.NebulaGraphParamUtil