whalex:
  module: com.meiya.whalex.db.module.file.HadoopServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.file.HadoopConfigHelper
  param: com.meiya.whalex.db.util.param.impl.file.HadoopParamUtil