whalex:
  module: com.meiya.whalex.db.module.ani.VerticaServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.ani.VerticaConfigHelper
  param: com.meiya.whalex.db.util.param.impl.ani.VerticaParamUtil