whalex:
  module: com.meiya.whalex.db.module.ani.GreenPlumServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.ani.GreenPlumConfigHelper
  param: com.meiya.whalex.db.util.param.impl.ani.GreenPlumParamUtil