whalex:
  module: com.meiya.whalex.db.module.ani.KingBaseEsServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.ani.KingBaseEsConfigHelper
  param: com.meiya.whalex.db.util.param.impl.ani.KingBaseEsParamUtil