whalex:
  module: com.meiya.whalex.db.module.ani.ClickHouseServiceImpl
  helper: com.meiya.whalex.db.util.helper.impl.ani.ClickHouseConfigHelper
  param: com.meiya.whalex.db.util.param.impl.ani.ClickHouseParamUtil